use super::adjacency::vertex_index;
use super::cap_fair::fair_cap_interior;
use super::cap_guard::{candidate_folds, candidate_pierces, CapCandidate, VertexTriangleIncidence};
use super::cap_minweight::{min_area_triangulation_any, rim_is_simple_3d};
use super::cap_refine::refine_and_relax;
use super::cap_support::{build_vertex_adjacency, gather_support_band, rim_outside_support};
use super::holes_gate::{
    border_perimeter_threshold, collect_boundary_loops, rim_exceeds_size_cap,
    rim_selection_qualifies,
};
use super::holes_walk::{build_boundary_maps, ear_clip_cap, push_cap_index, vertex_position};
use super::{
    copy_surviving_vertices, recompute_all_normals, remap_triangle_indices,
    validate_face_edit_buffers, validate_mesh_edit_options,
    validate_selection_against_triangle_count, EditVertex, FaceSelection, MeshEditBuffers,
    MeshEditError, MeshEditOptions, MeshEditReport, MeshEditResult, MeshEditWarning,
};
use glam::Vec3;
use std::collections::HashSet;

/// Loops at or above this many edges get the INTERPOLATED cap (refined interior
/// vertices + harmonic relaxation); smaller holes keep the plain planar cap.
const MIN_INTERPOLATED_LOOP: usize = 8;

/// Rims LONGER than this skip the interpolated cap and go straight to the
/// minimum-area membrane. Rim-density refinement + 128-iteration harmonic
/// relaxation costs seconds on a several-hundred-edge rim, and a deep tooth
/// socket that big folds the projection-based parameterization anyway — the
/// membrane is both the correct closure there and orders of magnitude faster,
/// keeping a 300–2000-edge socket well under the interactive budget.
const MAX_INTERPOLATED_LOOP: usize = 160;

/// Generous edge ceiling applied when a face selection is present: an explicit
/// selection is the operator's intent, so large marked rims still close. Bounded
/// well under the ear-clip's `u16` rim limit and within the measured cost of
/// the linked-ring ear-clip so a huge accidental selection cannot hang the tool.
pub(crate) const SELECTION_MAX_BOUNDARY_LOOP: usize = 20_000;

#[derive(Copy, Clone)]
struct FillInputCounts {
    vertices: usize,
    triangles: usize,
}

/// Index buffer plus vertices generated by interpolated caps, accumulated
/// across all filled loops before the final rebuild.
struct FillBuffers {
    indices: Vec<u32>,
    added_vertices: Vec<EditVertex>,
}

/// Per-run tallies that only become known once every boundary loop has been
/// walked: how many were closed and how many were skipped, broken down by
/// reason (scan border, size restraint, damage).
///
/// [`fill_holes`] folds every skip kind into one
/// [`MeshEditWarning::DegenerateGeometry`] per skipped loop (its long-standing
/// public contract) and mirrors the breakdown in the report's `skipped_*`
/// counters. The repair pipeline maps oversize skips to informational
/// `open_rims_left`; it disables the border guard, so `skipped_border` stays
/// zero there.
#[derive(Copy, Clone, Default)]
pub(crate) struct FillLoopStats {
    /// Boundary loops closed with a complete cap.
    pub(crate) filled: usize,
    /// Rims protected as the scan's natural outer boundary.
    pub(crate) skipped_border: usize,
    /// Rims skipped only because they exceed the effective size cap.
    pub(crate) skipped_oversize: usize,
    /// Rims skipped as non-simple, too short, degenerate, or with a cap that
    /// would pierce nearby surface.
    pub(crate) skipped_degenerate: usize,
}

/// Close boundary loops in a triangle mesh, exocad-style: every interior hole
/// closes by default; only the scan's natural OUTER boundary is protected.
///
/// Border protection (`options.protect_scan_border`, default on, whole-mesh
/// path only): a rim whose perimeter is at least half of the largest rim's
/// perimeter AND at least half of the mesh bounding-box diagonal is treated
/// as the open scan border and left alone. Everything else closes regardless
/// of size, bounded only by `options.max_boundary_loop` (sanity/perf ceiling)
/// and, when set, the optional `options.max_rim_perimeter_mm` restraint.
///
/// When `selection` is present, a rim is capped when the operator has marked at
/// least half of its owning faces (explicit intent): the selection loop ceiling
/// is lifted, and neither the border guard nor
/// the mm restraint applies.
///
/// Two rims that meet at a single vertex are pre-split during pinch handling so
/// both become independent simple loops that fill — previously the shared
/// junction dead-ended the walk and neither closed.
///
/// Caps are exocad-style "interpolated from surrounding edges": loops above
/// the interpolated-cap edge threshold are refined with generated interior
/// vertices (density matched to the rim, attributes per
/// `options.attribute_policy`), relaxed to the harmonic surface spanning the
/// rim, and faired against the fixed outside ring. Tiny holes keep a plain
/// planar cap on rim vertices only. Strongly curved rims whose planar
/// projection self-overlaps fall back to a projection-free minimum-area
/// triangulation. Every candidate cap is refused (never emitted) if it would
/// PIERCE itself or the surface around its rim.
///
/// Guards, each surfaced as one [`MeshEditWarning::DegenerateGeometry`] per
/// skipped loop in the returned report, with per-reason counts in the
/// report's `skipped_border_rims` / `skipped_oversize_rims` /
/// `skipped_damaged_rims`:
/// - border-protected rims stay open (border counter),
/// - loops longer than the effective edge cap, or over the mm restraint
///   (unselected only), are skipped (oversize counter),
/// - non-simple / numerically stalled loops, degenerate planar normals, and
///   piercing caps are skipped (damaged counter).
///
/// Loops left open because a selection did not cover their rim are NOT warned
/// about — that is requested behavior, not degeneracy.
///
/// # Errors
/// Returns typed validation errors for unsupported point clouds, malformed
/// triangle data, invalid selection masks, invalid options, or invalid rebuilt
/// triangle indices.
pub fn fill_holes(
    mesh: &MeshEditBuffers,
    selection: Option<&FaceSelection>,
    options: MeshEditOptions,
) -> Result<MeshEditResult, MeshEditError> {
    fill_holes_with_outcome(mesh, selection, options).map(|(result, _)| result)
}

/// [`fill_holes`] plus the per-loop skip breakdown the repair pipeline needs.
///
/// The returned [`MeshEditResult`] is exactly what [`fill_holes`] returns
/// (same mesh, same report, same warnings); the stats only add resolution.
pub(crate) fn fill_holes_with_outcome(
    mesh: &MeshEditBuffers,
    selection: Option<&FaceSelection>,
    options: MeshEditOptions,
) -> Result<(MeshEditResult, FillLoopStats), MeshEditError> {
    let options = validate_mesh_edit_options(options)?;
    validate_face_edit_buffers(mesh.topology, &mesh.vertices, &mesh.indices)?;
    if let Some(selection) = selection {
        validate_selection_against_triangle_count(mesh.triangle_count(), selection)?;
    }

    let counts = FillInputCounts {
        vertices: mesh.vertices.len(),
        triangles: mesh.triangle_count(),
    };

    if counts.triangles == 0 {
        return Ok((empty_fill_result(mesh, counts), FillLoopStats::default()));
    }

    // Weld STL-style soup to shared topology first (Close Holes path only), so
    // the boundary walk sees real rims instead of one phantom needle per
    // triangle. See [`apply_soup_weld`].
    let welded = apply_soup_weld(mesh, options.heal_boundary_rims)?;
    let mesh: &MeshEditBuffers = welded.as_ref().unwrap_or(mesh);

    // Pre-clean the cut line (opt-in via `heal_boundary_rims`): drop dangling
    // needle/lone triangles and weld near-coincident boundary vertices so a
    // jagged lasso cut (a digitally extracted tooth) yields clean simple rims
    // that cap — instead of dozens of "damaged" nick loops around the one socket
    // the operator wanted closed. Off by default (repair path), so the buffers
    // below stay byte-for-byte unchanged there.
    let healing = apply_rim_healing(mesh, selection, options.heal_boundary_rims);
    let healed_rims = healing.healed_rims;
    let (mesh, selection): (&MeshEditBuffers, Option<&FaceSelection>) = match &healing.mesh {
        Some(healed) => (healed, healing.selection.as_ref()),
        None => (mesh, selection),
    };

    // Two rims that meet at a single vertex both dead-end the boundary walk (the
    // junction has no unique successor), so today neither closes and the
    // operator sees "random" holes left open next to closed ones. Duplicate each
    // boundary-junction vertex per incident fan so every rim becomes a simple
    // loop that fills. A clean mesh (and repair's already bowtie-split input)
    // has no junctions, so this returns `None` and the path below runs on the
    // original buffers, byte-for-byte unchanged. Triangle count is preserved, so
    // the earlier selection-length validation still holds.
    let pinch_split = super::pinch::split_boundary_pinch_vertices(mesh)?;
    let mesh = pinch_split.as_ref().map_or(mesh, |(split, _)| split);

    let (next_boundary_vertex, owner_by_edge, boundary_starts) = build_boundary_maps(mesh)?;

    // No boundary half-edges at all means a closed mesh: nothing to fill and
    // nothing to warn about. (A non-empty rim with no manifold successors is a
    // pinched boundary — that must still fall through to the walk so each
    // junction is surfaced as a skipped loop, not silently ignored.)
    if boundary_starts.is_empty() {
        let buffers = FillBuffers {
            indices: mesh.indices.clone(),
            added_vertices: Vec::new(),
        };
        let stats = FillLoopStats::default();
        let result = finalize_fill_result(
            mesh,
            buffers,
            options.compact_vertices,
            counts,
            stats,
            healed_rims,
        )?;
        return Ok((result, stats));
    }

    let mut new_indices = mesh.indices.clone();
    let mut added_vertices: Vec<EditVertex> = Vec::new();
    let mut stats = FillLoopStats::default();

    // Vertex-vertex adjacency of the surrounding surface. Interpolated caps use
    // it to sample a support band OUTSIDE the rim so the fitted cap surface
    // picks up the real curvature there (a single planar rim carries none).
    // The triangle incidence backs the self-intersection guard's 2-ring
    // neighborhood query; both are built once and shared by every loop.
    let adjacency = build_vertex_adjacency(mesh);
    let incidence = VertexTriangleIncidence::build(mesh);
    let context = LoopFillContext {
        mesh,
        adjacency: &adjacency,
        incidence: &incidence,
    };

    // Phase 1: walk EVERY loop first. Border protection needs all rim
    // perimeters before any fill decision can be made.
    let loops = collect_boundary_loops(mesh, &next_boundary_vertex, &boundary_starts, &mut stats)?;

    // The scan-border guard applies only to the whole-mesh path: an explicit
    // selection is operator intent and may close anything it covers.
    let border_guard = options.protect_scan_border && selection.is_none();
    let border_threshold = if border_guard {
        border_perimeter_threshold(mesh, &loops)
    } else {
        f64::INFINITY
    };

    // Phase 2: gate and fill.
    for (boundary_loop, perimeter) in &loops {
        // A present selection is the operator's explicit target: qualify a rim
        // only when the mark covers at least half of it. A partially selected
        // rim staying open is requested behavior, not degeneracy — no warning.
        if let Some(selection) = selection {
            if !rim_selection_qualifies(boundary_loop, &owner_by_edge, selection) {
                continue;
            }
        }

        if border_guard && *perimeter >= border_threshold {
            stats.skipped_border += 1;
            continue;
        }

        if rim_exceeds_size_cap(boundary_loop, *perimeter, selection.is_some(), options) {
            stats.skipped_oversize += 1;
            continue;
        }

        // Only a COMPLETE cap (a full fan of loop_len - 2 triangles) counts as
        // a filled hole. A partial ear-clip result is never emitted, so the
        // index buffer only grows when the whole rim was triangulated.
        let filled = triangulate_loop(
            &context,
            boundary_loop,
            options,
            selection.is_some(),
            &mut new_indices,
            &mut added_vertices,
        )?;
        if filled {
            stats.filled += 1;
        } else {
            // Degenerate planar-cap normal, an incomplete ear-clip, or a
            // piercing cap: skipped.
            stats.skipped_degenerate += 1;
        }
    }

    let buffers = FillBuffers {
        indices: new_indices,
        added_vertices,
    };
    let result = finalize_fill_result(
        mesh,
        buffers,
        options.compact_vertices,
        counts,
        stats,
        healed_rims,
    )?;
    Ok((result, stats))
}

/// Weld an STL-style triangle soup back to shared topology on the Close Holes
/// path (`heal_boundary_rims`), a no-op on the repair path.
///
/// STL stores each triangle's corners as independent vertices, so in index space
/// every edge reads as a boundary and the whole model looks like a cloud of
/// disconnected needles — without this the cut-line healing "heals" one phantom
/// nick per triangle and no real rim is ever found. The weld preserves triangle
/// order, so any face selection stays valid; the repair pipeline runs its own
/// weld and keeps healing OFF, so it is byte-for-byte untouched here.
///
/// Returns the welded buffers (owned, so the borrow in
/// [`fill_holes_with_outcome`] outlives it) or `None` when nothing merged.
fn apply_soup_weld(
    mesh: &MeshEditBuffers,
    heal_boundary_rims: bool,
) -> Result<Option<MeshEditBuffers>, MeshEditError> {
    if heal_boundary_rims {
        super::topology::weld_soup_topology(mesh)
    } else {
        Ok(None)
    }
}

/// The healed mesh + remapped selection produced by the opt-in cut-line
/// pre-cleaning, owned so the borrows in [`fill_holes_with_outcome`] outlive it.
/// `mesh` is `None` when nothing needed healing (the caller keeps the original).
struct RimHealing {
    mesh: Option<MeshEditBuffers>,
    selection: Option<FaceSelection>,
    healed_rims: usize,
}

/// Run the cut-line pre-cleaning when `enabled`, projecting any face selection
/// onto the healed triangle order.
fn apply_rim_healing(
    mesh: &MeshEditBuffers,
    selection: Option<&FaceSelection>,
    enabled: bool,
) -> RimHealing {
    let outcome = if enabled {
        super::holes_cleanup::heal_boundary_rims(mesh)
    } else {
        None
    };
    let Some(outcome) = outcome else {
        return RimHealing {
            mesh: None,
            selection: None,
            healed_rims: 0,
        };
    };
    let selection = selection.map(|sel| outcome.remap_selection(sel));
    RimHealing {
        mesh: Some(outcome.mesh),
        selection,
        healed_rims: outcome.healed,
    }
}

/// Result for a mesh with no triangles: nothing to fill, everything zeroed.
fn empty_fill_result(mesh: &MeshEditBuffers, counts: FillInputCounts) -> MeshEditResult {
    MeshEditResult {
        mesh: mesh.clone(),
        report: MeshEditReport {
            input_vertices: counts.vertices,
            input_triangles: counts.triangles,
            output_vertices: counts.vertices,
            output_triangles: 0,
            removed_triangles: 0,
            filled_holes: 0,
            moved_vertices: 0,
            skipped_border_rims: 0,
            skipped_oversize_rims: 0,
            skipped_damaged_rims: 0,
            healed_rims: 0,
            warnings: Vec::new(),
        },
    }
}

#[allow(clippy::too_many_arguments)] // Cohesive fill-finalization parameters.
fn finalize_fill_result(
    mesh: &MeshEditBuffers,
    buffers: FillBuffers,
    compact_vertices: bool,
    counts: FillInputCounts,
    stats: FillLoopStats,
    healed_rims: usize,
) -> Result<MeshEditResult, MeshEditError> {
    // Public contract: one DegenerateGeometry warning per skipped loop,
    // whatever the skip reason (border and oversize rims included). The
    // report's skipped_* counters carry the per-reason breakdown.
    let warnings = vec![
        MeshEditWarning::DegenerateGeometry;
        stats.skipped_border + stats.skipped_oversize + stats.skipped_degenerate
    ];
    let filled_holes = stats.filled;
    let FillBuffers {
        indices,
        added_vertices,
    } = buffers;
    let mut all_vertices = mesh.vertices.clone();
    all_vertices.extend(added_vertices);
    let (mut vertices, indices) = if compact_vertices {
        let surviving_vertex_indices = surviving_vertex_indices(&indices)?;
        let (copied_vertices, remap) =
            copy_surviving_vertices(&all_vertices, &surviving_vertex_indices)?;
        let remapped_indices = remap_triangle_indices(&indices, &remap)?;
        (copied_vertices, remapped_indices)
    } else {
        (all_vertices, indices)
    };

    recompute_all_normals(&mut vertices, &indices)?;
    let output_vertices = vertices.len();
    let output_triangles = indices.len() / 3;

    Ok(MeshEditResult {
        mesh: MeshEditBuffers {
            topology: mesh.topology,
            vertices,
            indices,
        },
        report: MeshEditReport {
            input_vertices: counts.vertices,
            input_triangles: counts.triangles,
            output_vertices,
            output_triangles,
            removed_triangles: 0,
            filled_holes,
            moved_vertices: 0,
            skipped_border_rims: stats.skipped_border,
            skipped_oversize_rims: stats.skipped_oversize,
            skipped_damaged_rims: stats.skipped_degenerate,
            healed_rims,
            warnings,
        },
    })
}

fn surviving_vertex_indices(indices: &[u32]) -> Result<Vec<usize>, MeshEditError> {
    let mut seen = HashSet::new();
    let mut surviving = Vec::new();
    for (triangle_index, &raw_index) in indices.iter().enumerate() {
        let index = vertex_index(raw_index, triangle_index)?;
        if seen.insert(index) {
            surviving.push(index);
        }
    }
    Ok(surviving)
}

/// The surrounding mesh plus its precomputed vertex adjacency and triangle
/// incidence, shared by every loop fill in a run (adjacency backs the
/// interpolated cap's support band; incidence backs the piercing guard).
struct LoopFillContext<'a> {
    mesh: &'a MeshEditBuffers,
    adjacency: &'a [Vec<usize>],
    incidence: &'a VertexTriangleIncidence,
}

/// Whether a triangle with exactly the rim's vertex set already exists in the
/// mesh (any winding). Only ever called for 3-edge rims, so a linear scan of
/// the index buffer is fine.
fn triangle_already_exists(mesh: &MeshEditBuffers, boundary_loop: &[usize]) -> bool {
    let mut rim = [0usize; 3];
    rim.copy_from_slice(boundary_loop);
    rim.sort_unstable();
    mesh.indices.chunks_exact(3).any(|triangle| {
        let mut triple = [
            triangle[0] as usize,
            triangle[1] as usize,
            triangle[2] as usize,
        ];
        triple.sort_unstable();
        triple == rim
    })
}

/// Triangulate and emit one boundary loop. Returns `true` when a COMPLETE cap
/// was emitted (the hole is now closed), `false` when the loop was skipped.
///
/// Cap strategy, in order (first success wins; every candidate is a full,
/// watertight `loop_len - 2` fan — a partial cap is never emitted):
///
/// 1. Tiny holes (`< MIN_INTERPOLATED_LOOP`): the plain planar ear-clip fan.
/// 2. Larger holes: the exocad-style interpolated cap (refined interior +
///    harmonic relaxation), which continues curvature across the seam.
/// 3. Fallbacks for a refused/failed cap, EACH self-intersection guarded, first
///    non-piercing wins: the compact minimum-area membrane (uncapped in size
///    via hierarchical splitting — good for deep sockets and strongly wrapped
///    rims) then the flat ear-clip lid (good where the membrane grazes a wall).
///    Only for rims simple in 3D, so an hourglass crossing is never baked in.
/// 4. Selection path (explicit operator intent — exocad's rule that a lasso'd
///    socket ALWAYS closes): if every guarded candidate grazed nearby surface,
///    still emit the best watertight cover (membrane first, else the flat lid).
///    Whole-mesh auto-close does not do this — it stays conservative and
///    refuses, so it never silently bakes a self-intersection into a scan.
///
/// A 3-edge rim around a lone free-standing triangle is never capped on any
/// path: its only cover is the triangle's reverse twin, a zero-volume doubled
/// sliver. (The pre-cleaning pass removes such triangles up front when enabled.)
#[allow(clippy::too_many_arguments)] // Cohesive per-loop capping parameters.
fn triangulate_loop(
    context: &LoopFillContext<'_>,
    boundary_loop: &[usize],
    options: MeshEditOptions,
    has_selection: bool,
    new_indices: &mut Vec<u32>,
    added_vertices: &mut Vec<EditVertex>,
) -> Result<bool, MeshEditError> {
    let mesh = context.mesh;
    let loop_len = boundary_loop.len();
    if loop_len < 3 {
        return Ok(false);
    }
    let rim_positions: Vec<Vec3> = boundary_loop
        .iter()
        .map(|&vertex_index| vertex_position(mesh, vertex_index))
        .collect::<Result<_, _>>()?;

    // A lone free-standing triangle's only cap is its reverse twin — never emit
    // that doubled sliver, on any path.
    if loop_len == 3 && triangle_already_exists(mesh, boundary_loop) {
        return Ok(false);
    }

    let support = gather_support_band(mesh, boundary_loop, context.adjacency);
    let ear = ear_clip_cap(mesh, boundary_loop)?;

    // 1) Tiny holes: the plain planar ear-clip fan, guarded.
    if !ear.is_empty()
        && loop_len < MIN_INTERPOLATED_LOOP
        && !plain_cap_pierces(
            context,
            boundary_loop,
            &rim_positions,
            &support,
            &ear,
            added_vertices,
        )
    {
        emit_plain_cap(new_indices, boundary_loop, &ear)?;
        return Ok(true);
    }

    // 2) Larger holes: the exocad-style interpolated cap (bounded — a socket
    // rim past `MAX_INTERPOLATED_LOOP` skips straight to the fast membrane).
    if !ear.is_empty()
        && (MIN_INTERPOLATED_LOOP..=MAX_INTERPOLATED_LOOP).contains(&loop_len)
        && emit_interpolated_cap(
            context,
            boundary_loop,
            &rim_positions,
            &support,
            ear.clone(),
            options,
            new_indices,
            added_vertices,
        )?
    {
        return Ok(true);
    }

    // 3) Guarded fallbacks, first non-piercing wins. The hierarchical
    // minimum-area membrane lifts the old 256-edge cap so deep tooth sockets
    // (hundreds to thousands of rim edges) get a full watertight cover.
    let simple3d = rim_is_simple_3d(&rim_positions);
    let membrane = if simple3d {
        min_area_triangulation_any(&rim_positions)
    } else {
        None
    };
    let ear_lid = (!ear.is_empty()).then_some(ear);
    for cap in [membrane.as_ref(), ear_lid.as_ref()].into_iter().flatten() {
        if !plain_cap_pierces(
            context,
            boundary_loop,
            &rim_positions,
            &support,
            cap,
            added_vertices,
        ) {
            emit_plain_cap(new_indices, boundary_loop, cap)?;
            return Ok(true);
        }
    }

    // 4) Selection path: the operator marked this rim — it must close. Emit the
    // best watertight cover even if it grazes nearby surface.
    if has_selection {
        if let Some(cap) = membrane.as_ref().or(ear_lid.as_ref()) {
            emit_plain_cap(new_indices, boundary_loop, cap)?;
            return Ok(true);
        }
    }
    Ok(false)
}

/// Whether a rim-only (no generated interior) cap pierces itself or the
/// surrounding surface within the support band.
#[allow(clippy::too_many_arguments)] // Cohesive plain-cap guard parameters.
fn plain_cap_pierces(
    context: &LoopFillContext<'_>,
    boundary_loop: &[usize],
    rim_positions: &[Vec3],
    support: &super::cap_support::SupportBand,
    triangles: &[[usize; 3]],
    added_vertices: &[EditVertex],
) -> bool {
    let candidate = CapCandidate {
        rim: boundary_loop,
        rim_positions,
        generated: &[],
        generated_base: context.mesh.vertices.len() + added_vertices.len(),
        triangles,
    };
    candidate_pierces(
        context.mesh,
        context.incidence,
        &support.vertex_set,
        &candidate,
    )
}

/// Emit a rim-only cap (local indices resolve directly into the rim).
fn emit_plain_cap(
    new_indices: &mut Vec<u32>,
    boundary_loop: &[usize],
    cap_triangles: &[[usize; 3]],
) -> Result<(), MeshEditError> {
    for triangle in cap_triangles {
        for &local in triangle {
            push_cap_index(new_indices, boundary_loop[local])?;
        }
    }
    Ok(())
}

/// Interpolated-cap tail of [`triangulate_loop`]: refine with interior
/// vertices matched to the rim edge density, relax to the harmonic surface
/// spanning the 3D rim, fair the interior against the FIXED outside ring so
/// curvature continues across the seam, and emit — unless the (faired, then
/// unfaired) cap pierces the surroundings, in which case the loop is refused.
#[allow(clippy::too_many_arguments)] // Internal tail call sharing one context.
fn emit_interpolated_cap(
    context: &LoopFillContext<'_>,
    boundary_loop: &[usize],
    rim_positions: &[Vec3],
    support: &super::cap_support::SupportBand,
    cap_triangles: Vec<[usize; 3]>,
    options: MeshEditOptions,
    new_indices: &mut Vec<u32>,
    added_vertices: &mut Vec<EditVertex>,
) -> Result<bool, MeshEditError> {
    let mesh = context.mesh;
    let loop_len = boundary_loop.len();
    let rim: Vec<EditVertex> = boundary_loop
        .iter()
        .map(|&vertex_index| {
            mesh.vertices
                .get(vertex_index)
                .copied()
                .ok_or_else(|| MeshEditError::MalformedMesh {
                    reason: format!(
                        "boundary loop vertex index {vertex_index} is out of range for \
                         vertex_count {}",
                        mesh.vertices.len()
                    ),
                })
        })
        .collect::<Result<_, _>>()?;
    let mut cap = refine_and_relax(
        &rim,
        &support.positions,
        cap_triangles,
        options.attribute_policy.generated_vertex_policy,
    );

    let unfaired: Vec<Vec3> = cap
        .generated
        .iter()
        .map(|vertex| Vec3::from_array(vertex.position))
        .collect();
    let mut faired: Vec<Vec3> = rim_positions
        .iter()
        .chain(unfaired.iter())
        .copied()
        .collect();
    let rim_support = rim_outside_support(mesh, boundary_loop, context.adjacency);
    fair_cap_interior(&mut faired, loop_len, &cap.triangles, &rim_support);

    // Guard the faired cap; if fairing itself caused a fold, fall back to the
    // unfaired cap before refusing the hole outright.
    let generated_base = mesh.vertices.len() + added_vertices.len();
    let candidates: [&[Vec3]; 2] = [&faired[loop_len..], &unfaired];
    let accepted = candidates.into_iter().find(|interior| {
        let candidate = CapCandidate {
            rim: boundary_loop,
            rim_positions,
            generated: interior,
            generated_base,
            triangles: &cap.triangles,
        };
        !candidate_folds(&candidate)
            && !candidate_pierces(mesh, context.incidence, &support.vertex_set, &candidate)
    });
    // `find` hands back the winning slice (faired preferred, else unfaired).
    let Some(interior) = accepted else {
        return Ok(false);
    };
    for (vertex, position) in cap.generated.iter_mut().zip(interior) {
        vertex.position = position.to_array();
    }

    for triangle in cap.triangles {
        for local in triangle {
            let global = if local < loop_len {
                boundary_loop[local]
            } else {
                generated_base + (local - loop_len)
            };
            push_cap_index(new_indices, global)?;
        }
    }
    added_vertices.extend(cap.generated);
    Ok(true)
}
