use super::MeshEditError;

/// A product-neutral vertex payload used by mesh-edit kernels.
///
/// Adapters must copy the complete payload for surviving vertices. Kernels
/// must not weld vertices just because positions match: dental formats often
/// duplicate a position with different UVs, colors, or normals.
#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct EditVertex {
    /// Position in the caller's canonical units/frame.
    pub position: [f32; 3],
    /// Vertex normal. Topology-changing operations recompute this explicitly.
    pub normal: [f32; 3],
    /// sRGBA color, packed 0..=255. White means no color in many adapters.
    pub color: [u8; 4],
    /// Texture coordinates. `[0.0, 0.0]` means absent in many adapters.
    pub uv: [f32; 2],
}

impl EditVertex {
    /// Construct a white vertex with zero normal and zero UV.
    #[must_use]
    pub const fn at(position: [f32; 3]) -> Self {
        Self {
            position,
            normal: [0.0; 3],
            color: [255, 255, 255, 255],
            uv: [0.0; 2],
        }
    }
}

/// Whether the input carries triangle connectivity or just points.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Default)]
pub enum MeshTopology {
    /// Triangle mesh: indices are interpreted in chunks of three.
    #[default]
    TriangleMesh,
    /// Point cloud: face edit operations must reject it.
    PointCloud,
}

/// Product-neutral editable mesh buffers.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct MeshEditBuffers {
    /// Vertices in caller-defined canonical frame/units.
    pub vertices: Vec<EditVertex>,
    /// Triangle indices into `vertices`.
    pub indices: Vec<u32>,
    /// Topology kind.
    pub topology: MeshTopology,
}

impl MeshEditBuffers {
    /// Number of triangles represented by `indices`.
    #[must_use]
    pub fn triangle_count(&self) -> usize {
        self.indices.len() / 3
    }
}

/// Policy for attributes generated by operations that create vertices.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum GeneratedVertexPolicy {
    /// Interpolate or average nearby/boundary attributes when possible.
    InterpolateBoundary,
    /// Use deterministic neutral fallback attributes.
    NeutralFallback,
}

/// Attribute policy shared by mesh edit kernels.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct MeshEditAttributePolicy {
    /// Policy for new vertices generated by fill/repair operations.
    pub generated_vertex_policy: GeneratedVertexPolicy,
}

impl Default for MeshEditAttributePolicy {
    fn default() -> Self {
        Self {
            generated_vertex_policy: GeneratedVertexPolicy::InterpolateBoundary,
        }
    }
}

/// Options shared by mesh edit kernels.
// Not `Eq`: `max_rim_perimeter_mm` carries an `f32`.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct MeshEditOptions {
    /// Whether operations may drop unreferenced vertices.
    pub compact_vertices: bool,
    /// Maximum boundary loop length (edge count) for conservative hole filling.
    /// This stays a hard safety ceiling even when `max_rim_perimeter_mm` is set.
    pub max_boundary_loop: usize,
    /// Attribute policy for generated vertices.
    pub attribute_policy: MeshEditAttributePolicy,
    /// Optional cap on a boundary rim's PERIMETER, in mesh units (mm), for
    /// whole-mesh (unselected) hole filling. `None` means no perimeter
    /// restraint: every interior hole closes (the scan border is protected by
    /// `protect_scan_border` instead). When a face selection is present the
    /// operator's explicit intent wins and this mm cap is ignored.
    pub max_rim_perimeter_mm: Option<f32>,
    /// Whole-mesh (unselected) fill only: protect the scan's natural OUTER
    /// boundary. A rim is treated as scan border when its perimeter is both
    /// at least half of the largest rim's perimeter and at least half of the
    /// mesh bounding-box diagonal; border rims stay open (reported per
    /// [`MeshEditReport::skipped_border_rims`]) while every other rim closes
    /// regardless of size. Repair-style callers that only ever cap pinholes
    /// switch this off.
    pub protect_scan_border: bool,
    /// Hole filling only: heal the cut line before the boundary walk. When on,
    /// dangling needle/lone triangles are dropped to a fixpoint and
    /// near-coincident boundary vertices are welded, so a jagged lasso cut (a
    /// digitally extracted tooth) yields clean simple rims that cap instead of
    /// dozens of "damaged" nick loops. The Close Holes path enables it; the
    /// repair pipeline leaves it OFF and stays byte-for-byte unchanged.
    pub heal_boundary_rims: bool,
}

impl Default for MeshEditOptions {
    fn default() -> Self {
        Self {
            compact_vertices: false,
            max_boundary_loop: 8192,
            attribute_policy: MeshEditAttributePolicy::default(),
            max_rim_perimeter_mm: None,
            protect_scan_border: true,
            heal_boundary_rims: false,
        }
    }
}

impl MeshEditOptions {
    /// Validate option values before an edit operation.
    ///
    /// # Errors
    /// Returns [`MeshEditError::InvalidOptions`] if a value is nonsensical.
    pub fn validate(self) -> Result<Self, MeshEditError> {
        if self.max_boundary_loop == 0 {
            return Err(MeshEditError::InvalidOptions {
                reason: "max_boundary_loop must be greater than zero".to_string(),
            });
        }
        if let Some(perimeter_mm) = self.max_rim_perimeter_mm {
            if !perimeter_mm.is_finite() || perimeter_mm <= 0.0 {
                return Err(MeshEditError::InvalidOptions {
                    reason: "max_rim_perimeter_mm must be finite and greater than zero".to_string(),
                });
            }
        }
        Ok(self)
    }
}

/// A face-selection mask, stored in triangle order.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FaceSelection {
    selected_faces: Vec<bool>,
}

impl FaceSelection {
    /// Construct a selection without validating its length.
    #[must_use]
    pub fn new(selected_faces: Vec<bool>) -> Self {
        Self { selected_faces }
    }

    /// Construct and validate a selection against a triangle count.
    ///
    /// # Errors
    /// Returns [`MeshEditError::InvalidSelectionLength`] on length mismatch.
    pub fn try_for_triangle_count(
        triangle_count: usize,
        selected_faces: Vec<bool>,
    ) -> Result<Self, MeshEditError> {
        let selection = Self::new(selected_faces);
        selection.validate_for_triangle_count(triangle_count)?;
        Ok(selection)
    }

    /// Borrow the underlying mask.
    #[must_use]
    pub fn as_slice(&self) -> &[bool] {
        &self.selected_faces
    }

    /// Number of faces represented by this selection.
    #[must_use]
    pub fn len(&self) -> usize {
        self.selected_faces.len()
    }

    /// Whether the mask is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.selected_faces.is_empty()
    }

    /// Number of selected faces.
    #[must_use]
    pub fn selected_count(&self) -> usize {
        self.selected_faces
            .iter()
            .filter(|selected| **selected)
            .count()
    }

    /// Validate the mask length against a triangle count.
    ///
    /// # Errors
    /// Returns [`MeshEditError::InvalidSelectionLength`] on mismatch.
    pub fn validate_for_triangle_count(&self, triangle_count: usize) -> Result<(), MeshEditError> {
        let actual = self.len();
        if actual != triangle_count {
            return Err(MeshEditError::InvalidSelectionLength {
                expected: triangle_count,
                actual,
            });
        }
        Ok(())
    }
}

/// Non-fatal notes produced by edit kernels.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MeshEditWarning {
    /// Degenerate geometry was skipped.
    DegenerateGeometry,
}

/// Summary information for a mesh edit operation.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct MeshEditReport {
    /// Input vertex count.
    pub input_vertices: usize,
    /// Input triangle count.
    pub input_triangles: usize,
    /// Output vertex count.
    pub output_vertices: usize,
    /// Output triangle count.
    pub output_triangles: usize,
    /// Removed triangle count.
    pub removed_triangles: usize,
    /// Filled hole count.
    pub filled_holes: usize,
    /// Vertices whose position was actually changed (relaxation ops). Lets a
    /// caller detect a content no-op — e.g. smoothing an already-converged
    /// region moves nothing and must not dirty the session.
    pub moved_vertices: usize,
    /// Hole filling: rims left open by the scan-border guard (the mesh's
    /// natural boundary, not damage).
    pub skipped_border_rims: usize,
    /// Hole filling: rims left open by the edge-count ceiling or the optional
    /// mm perimeter restraint.
    pub skipped_oversize_rims: usize,
    /// Hole filling: rims refused as damaged — non-simple, numerically
    /// stalled, or a cap that would pierce itself or nearby surface.
    pub skipped_damaged_rims: usize,
    /// Hole filling: cut-line defects healed by the pre-cleaning pass before
    /// capping — dangling needle/lone triangles dropped plus near-coincident
    /// boundary vertices welded. Zero unless `heal_boundary_rims` is enabled.
    pub healed_rims: usize,
    /// Non-fatal warnings. For hole filling this stays one entry per skipped
    /// loop of ANY kind (long-standing contract); the three `skipped_*`
    /// counters above break the same total down by reason.
    pub warnings: Vec<MeshEditWarning>,
}

/// A completed mesh edit result.
#[derive(Clone, Debug, PartialEq)]
pub struct MeshEditResult {
    /// Edited mesh buffers.
    pub mesh: MeshEditBuffers,
    /// Operation report.
    pub report: MeshEditReport,
}
