use super::{
    write_f32_le, write_i32_le, MeshWriteFormat, MeshWriteOptions, MeshWriteReport,
    MeshWriteWarning,
};
use crate::error::FormatError;
use occluview_core::{Mesh, MeshKind};
use std::io::Write;

pub(super) fn write_mesh<W: Write>(
    writer: &mut W,
    mesh: &Mesh,
    options: MeshWriteOptions,
    report: &mut MeshWriteReport,
) -> Result<(), FormatError> {
    if mesh.has_vertex_colors() && !options.include_vertex_colors {
        report.warn(MeshWriteWarning::VertexColorsNotWritten);
    }
    if mesh.has_uvs() {
        report.warn(MeshWriteWarning::UvsNotWritten);
    }
    if mesh.texture().is_some() {
        report.warn(MeshWriteWarning::TextureImageNotWritten);
    }

    let vertex_count = mesh.vertices().len();
    let face_count = if mesh.kind() == MeshKind::TriangleMesh {
        mesh.triangle_count()
    } else {
        0
    };

    write!(
        writer,
        "ply\nformat binary_little_endian 1.0\ncomment Generated by OccluView\nelement vertex {vertex_count}\nproperty float x\nproperty float y\nproperty float z\n"
    )?;
    if options.include_normals {
        write!(
            writer,
            "property float nx\nproperty float ny\nproperty float nz\n"
        )?;
    }
    if options.include_vertex_colors && mesh.has_vertex_colors() {
        write!(
            writer,
            "property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n"
        )?;
    }
    if mesh.kind() == MeshKind::TriangleMesh {
        write!(
            writer,
            "element face {face_count}\nproperty list uchar int vertex_indices\n"
        )?;
    }
    writeln!(writer, "end_header")?;

    for vertex in mesh.vertices() {
        write_f32_le(writer, vertex.position[0])?;
        write_f32_le(writer, vertex.position[1])?;
        write_f32_le(writer, vertex.position[2])?;
        if options.include_normals {
            write_f32_le(writer, vertex.normal[0])?;
            write_f32_le(writer, vertex.normal[1])?;
            write_f32_le(writer, vertex.normal[2])?;
        }
        if options.include_vertex_colors && mesh.has_vertex_colors() {
            writer.write_all(&vertex.color)?;
        }
    }

    if mesh.kind() == MeshKind::TriangleMesh {
        for triangle in mesh.indices().chunks_exact(3) {
            writer.write_all(&[3])?;
            for index in triangle {
                write_i32_le(
                    writer,
                    i32::try_from(*index).map_err(|_| FormatError::Malformed {
                        format: MeshWriteFormat::PlyBinaryLittleEndian.label(),
                        offset: 0,
                        reason: "triangle index exceeds i32".to_string(),
                    })?,
                )?;
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use occluview_core::{MeshTexture, Vertex};

    fn sample_point_cloud() -> Mesh {
        let mut mesh = Mesh::point_cloud(
            Some("cloud".to_string()),
            vec![Vertex::at(glam::Vec3::new(1.0, 2.0, 3.0))
                .with_normal(glam::Vec3::new(4.0, 5.0, 6.0))
                .with_color([11, 22, 33, 44])
                .with_uv([0.25, 0.75])],
        );
        mesh.set_texture(MeshTexture::new(1, 1, vec![9, 8, 7, 6]));
        mesh
    }

    #[test]
    fn preserves_vertex_color_bytes_and_reports_loss_warnings() {
        let mesh = sample_point_cloud();
        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert_eq!(written.format, MeshWriteFormat::PlyBinaryLittleEndian);
        assert_eq!(written.vertices, 1);
        assert_eq!(written.triangles, 0);
        assert!(written.warnings.contains(&MeshWriteWarning::UvsNotWritten));
        assert!(written
            .warnings
            .contains(&MeshWriteWarning::TextureImageNotWritten));
        assert!(!written
            .warnings
            .contains(&MeshWriteWarning::VertexColorsNotWritten));

        let header_end = bytes
            .windows(b"end_header\n".len())
            .position(|window| window == b"end_header\n")
            .expect("end header")
            + b"end_header\n".len();
        let color_offset = header_end + 24;
        assert_eq!(&bytes[color_offset..color_offset + 4], [11, 22, 33, 44]);
    }
}
