use super::vertex_color::baked_colors;
use super::{
    write_f32_le, write_i32_le, MeshWriteFormat, MeshWriteOptions, MeshWriteReport,
    MeshWriteWarning,
};
use crate::error::FormatError;
use occluview_core::{Mesh, MeshKind};
use std::io::Write;

#[cfg(test)]
use super::vertex_color::sample;

pub(super) fn write_mesh<W: Write>(
    writer: &mut W,
    mesh: &Mesh,
    options: MeshWriteOptions,
    report: &mut MeshWriteReport,
) -> Result<(), FormatError> {
    // PLY has no texture element, so an attached atlas is baked into per-vertex
    // RGBA (the form a scanner's PLY uses). See `vertex_color`.
    let baked = baked_colors(mesh, &options);
    let plan = VertexPlan {
        colors: options.include_vertex_colors && (baked.is_some() || mesh.has_vertex_colors()),
        normals: options.include_normals,
        // No image means no `s`/`t`: a reader that sees coordinates without an
        // image enters an empty texture mode and draws the scan white. A scan
        // with no atlas keeps its coordinates.
        uvs: options.include_uvs && mesh.has_uvs() && baked.is_none(),
        baked: baked.as_deref(),
    };
    report_losses(mesh, &options, plan, report);

    write_header(writer, mesh, plan)?;
    write_vertices(writer, mesh, plan)?;
    write_faces(writer, mesh)?;

    Ok(())
}

/// What the vertex element of this export is going to carry.
///
/// One value rather than four loose flags, decided once so the header and the
/// rows it describes cannot disagree about the property list.
#[derive(Copy, Clone)]
struct VertexPlan<'a> {
    /// Write per-vertex RGBA.
    colors: bool,
    /// Write per-vertex normals.
    normals: bool,
    /// Write per-vertex `s`/`t`.
    uvs: bool,
    /// Baked colours that replace the vertices' own, when an atlas was sampled.
    baked: Option<&'a [[u8; 4]]>,
}

/// Report what this write cannot carry.
///
/// Every loss is about the mesh rather than about the format: the writer either
/// writes a property or says why it did not.
fn report_losses(
    mesh: &Mesh,
    options: &MeshWriteOptions,
    plan: VertexPlan<'_>,
    report: &mut MeshWriteReport,
) {
    // The baked atlas is what the renderer shows by default, so it is the
    // colour written. A mesh that also carries its own per-vertex colours (a
    // painted or occlusion-marked scan) therefore loses them, and has to say so.
    let colors_replaced = plan.baked.is_some() && mesh.has_vertex_colors();
    if mesh.has_vertex_colors() && (!options.include_vertex_colors || colors_replaced) {
        report.warn(MeshWriteWarning::VertexColorsNotWritten);
    }
    if mesh.has_uvs() && !plan.uvs {
        report.warn(MeshWriteWarning::UvsNotWritten);
    }
    if mesh.texture().is_some() && plan.baked.is_none() {
        report.warn(MeshWriteWarning::TextureImageNotWritten);
    }
}

fn write_header<W: Write>(
    writer: &mut W,
    mesh: &Mesh,
    plan: VertexPlan<'_>,
) -> Result<(), FormatError> {
    let vertex_count = mesh.vertices().len();
    let face_count = if mesh.kind() == MeshKind::TriangleMesh {
        mesh.triangle_count()
    } else {
        0
    };
    writeln!(writer, "ply")?;
    writeln!(writer, "format binary_little_endian 1.0")?;
    writeln!(writer, "comment Generated by OccluView")?;
    writeln!(writer, "element vertex {vertex_count}")?;
    writeln!(writer, "property float x")?;
    writeln!(writer, "property float y")?;
    writeln!(writer, "property float z")?;
    if plan.normals {
        writeln!(writer, "property float nx")?;
        writeln!(writer, "property float ny")?;
        writeln!(writer, "property float nz")?;
    }
    if plan.colors {
        writeln!(writer, "property uchar red")?;
        writeln!(writer, "property uchar green")?;
        writeln!(writer, "property uchar blue")?;
        writeln!(writer, "property uchar alpha")?;
    }
    if plan.uvs {
        writeln!(writer, "property float s")?;
        writeln!(writer, "property float t")?;
    }
    if mesh.kind() == MeshKind::TriangleMesh {
        writeln!(writer, "element face {face_count}")?;
        writeln!(writer, "property list uchar int vertex_indices")?;
    }
    writeln!(writer, "end_header")?;
    Ok(())
}

fn write_vertices<W: Write>(
    writer: &mut W,
    mesh: &Mesh,
    plan: VertexPlan<'_>,
) -> Result<(), FormatError> {
    for (index, vertex) in mesh.vertices().iter().enumerate() {
        write_f32_le(writer, vertex.position[0])?;
        write_f32_le(writer, vertex.position[1])?;
        write_f32_le(writer, vertex.position[2])?;
        if plan.normals {
            write_f32_le(writer, vertex.normal[0])?;
            write_f32_le(writer, vertex.normal[1])?;
            write_f32_le(writer, vertex.normal[2])?;
        }
        if plan.colors {
            let color = plan.baked.map_or(vertex.color, |baked| baked[index]);
            writer.write_all(&color)?;
        }
        if plan.uvs {
            write_f32_le(writer, vertex.uv[0])?;
            write_f32_le(writer, vertex.uv[1])?;
        }
    }
    Ok(())
}

fn write_faces<W: Write>(writer: &mut W, mesh: &Mesh) -> Result<(), FormatError> {
    if mesh.kind() != MeshKind::TriangleMesh {
        return Ok(());
    }
    for triangle in mesh.indices().as_chunks::<3>().0 {
        writer.write_all(&[3])?;
        for index in triangle {
            write_i32_le(
                writer,
                i32::try_from(*index).map_err(|_| FormatError::Malformed {
                    format: MeshWriteFormat::PlyBinaryLittleEndian.label(),
                    offset: 0,
                    reason: "triangle index exceeds i32".to_string(),
                })?,
            )?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use occluview_core::{MeshTexture, Vertex};

    fn sample_point_cloud() -> Mesh {
        let mut mesh = Mesh::point_cloud(
            Some("cloud".to_string()),
            vec![Vertex::at(glam::Vec3::new(1.0, 2.0, 3.0))
                .with_normal(glam::Vec3::new(4.0, 5.0, 6.0))
                .with_color([11, 22, 33, 44])
                .with_uv([0.25, 0.75])],
        );
        mesh.set_texture(MeshTexture::new(1, 1, vec![9, 8, 7, 6]));
        mesh
    }

    /// A triangle whose three UVs land on three different texels of a 2x2
    /// atlas, so a reordered or mirrored sample cannot pass by accident.
    fn textured_triangle() -> Mesh {
        let mut mesh = Mesh::new(
            Some("arch".to_string()),
            vec![
                Vertex::at(glam::Vec3::ZERO).with_uv([0.25, 0.25]),
                Vertex::at(glam::Vec3::X).with_uv([0.75, 0.25]),
                Vertex::at(glam::Vec3::Y).with_uv([0.25, 0.75]),
            ],
            vec![0, 1, 2],
        )
        .expect("a triangle mesh");
        mesh.set_texture(MeshTexture::new(
            2,
            2,
            vec![
                255, 0, 0, 255, // top-left, red
                0, 255, 0, 255, // top-right, green
                0, 0, 255, 255, // bottom-left, blue
                255, 255, 0, 255, // bottom-right, yellow
            ],
        ));
        mesh
    }

    /// A textured export carries colour on the vertices and no encoded image in
    /// the header, so the result is a single file.
    #[test]
    fn a_scan_texture_is_baked_into_per_vertex_colour() {
        let mesh = textured_triangle();
        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert!(
            !written
                .warnings
                .contains(&MeshWriteWarning::TextureImageNotWritten),
            "the colour was written: {:?}",
            written.warnings
        );
        let header_end = bytes
            .windows(b"end_header\n".len())
            .position(|window| window == b"end_header\n")
            .expect("end header");
        let header = String::from_utf8_lossy(&bytes[..header_end]);
        assert!(
            header.contains("property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n"),
            "the colour is per vertex, the way a scanner writes it:\n{header}"
        );
        assert!(
            !header.contains("OccluViewTexture"),
            "no image may be encoded into the header:\n{header}"
        );
        assert!(
            !header.contains("TextureFile"),
            "nothing is written beside this file, so the header must not name an image"
        );
        // No image travels, so the coordinates would point at nothing. A reader
        // that sees s/t without a texture switches to an empty texture mode and
        // draws the scan white; a scanner's own coloured PLY carries none.
        assert!(
            !header.contains("property float s"),
            "no coordinates are written once the colour is baked:\n{header}"
        );

        // The colour each vertex samples is the colour the viewer showed.
        let read = crate::ply::read(&bytes).expect("read back the exported ply");
        assert!(read.has_vertex_colors(), "the colour came back on vertices");
        assert!(read.texture().is_none(), "no phantom image is attached");
        assert!(!read.has_uvs(), "no dangling coordinates are attached");
        assert_eq!(read.vertices()[0].color, [255, 0, 0, 255]);
        assert_eq!(read.vertices()[1].color, [0, 255, 0, 255]);
        assert_eq!(read.vertices()[2].color, [0, 0, 255, 255]);
    }

    /// A mesh that carries BOTH an atlas and its own per-vertex colours — a
    /// painted or occlusion-marked HPS scan is exactly that — exports the atlas,
    /// because that is what the viewer shows by default, and reports the
    /// colours it replaced rather than dropping them without a word.
    #[test]
    fn replacing_real_vertex_colours_with_the_atlas_is_reported() {
        let mut mesh = textured_triangle();
        let mut vertices = mesh.vertices().to_vec();
        vertices[0].color = [10, 20, 30, 255];
        vertices[1].color = [40, 50, 60, 255];
        vertices[2].color = [70, 80, 90, 255];
        mesh =
            Mesh::new(Some("arch".to_string()), vertices, vec![0, 1, 2]).expect("a triangle mesh");
        mesh.set_texture(MeshTexture::new(
            2,
            2,
            vec![
                255, 0, 0, 255, 0, 255, 0, 255, 0, 0, 255, 255, 255, 255, 0, 255,
            ],
        ));
        assert!(mesh.has_vertex_colors() && mesh.texture().is_some());

        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert!(
            written
                .warnings
                .contains(&MeshWriteWarning::VertexColorsNotWritten),
            "the colours the atlas replaced must be reported: {:?}",
            written.warnings
        );
        let read = crate::ply::read(&bytes).expect("read back");
        assert_eq!(
            read.vertices()[0].color,
            [255, 0, 0, 255],
            "the atlas colour is what was written"
        );
    }

    /// With no atlas there is nothing to bake, so a mesh's own colours go out
    /// unchanged and nothing is reported as lost.
    #[test]
    fn vertex_colours_alone_are_written_without_a_warning() {
        let mut mesh = textured_triangle();
        mesh.clear_texture();
        let mut vertices = mesh.vertices().to_vec();
        vertices[0].color = [10, 20, 30, 255];
        mesh =
            Mesh::new(Some("arch".to_string()), vertices, vec![0, 1, 2]).expect("a triangle mesh");
        assert!(mesh.has_vertex_colors() && mesh.texture().is_none());

        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert!(
            !written
                .warnings
                .contains(&MeshWriteWarning::VertexColorsNotWritten),
            "nothing was lost: {:?}",
            written.warnings
        );
        let read = crate::ply::read(&bytes).expect("read back");
        assert_eq!(read.vertices()[0].color, [10, 20, 30, 255]);
    }

    /// A mesh without a texture still carries its mapping, as per-vertex
    /// properties, so the coordinates are not silently dropped on the way out.
    #[test]
    fn coordinates_survive_without_an_image() {
        let mut mesh = textured_triangle();
        mesh.clear_texture();
        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert!(!written.warnings.contains(&MeshWriteWarning::UvsNotWritten));
        let header_end = bytes
            .windows(b"end_header\n".len())
            .position(|window| window == b"end_header\n")
            .expect("end header");
        let header = String::from_utf8_lossy(&bytes[..header_end]);
        assert!(header.contains("property float s\nproperty float t\n"));
        assert!(!header.contains("texcoord"));

        let read = crate::ply::read(&bytes).expect("read back");
        assert!(read.has_uvs());
        assert_eq!(read.vertices()[2].uv, [0.25, 0.75]);
    }

    #[test]
    fn preserves_vertex_color_bytes_and_reports_loss_warnings() {
        let mesh = sample_point_cloud();
        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert_eq!(written.format, MeshWriteFormat::PlyBinaryLittleEndian);
        assert_eq!(written.vertices, 1);
        assert_eq!(written.triangles, 0);
        // A point cloud has no faces for a texture to map through, so the image
        // is dropped and said so. The coordinates themselves are not lost: they
        // go out as per-vertex `s`/`t`.
        assert!(written
            .warnings
            .contains(&MeshWriteWarning::TextureImageNotWritten));
        assert!(!written.warnings.contains(&MeshWriteWarning::UvsNotWritten));
        assert!(!written
            .warnings
            .contains(&MeshWriteWarning::VertexColorsNotWritten));

        let header_end = bytes
            .windows(b"end_header\n".len())
            .position(|window| window == b"end_header\n")
            .expect("end header")
            + b"end_header\n".len();
        let color_offset = header_end + 24;
        assert_eq!(&bytes[color_offset..color_offset + 4], [11, 22, 33, 44]);
    }

    /// An unusable texture must not be promised, and must not abort the export.
    ///
    /// A texture whose decoded surface does not match its dimensions would make
    /// a sampler read out of bounds; the writer drops it and says so.
    #[test]
    fn an_image_whose_pixels_disagree_with_its_size_is_not_baked() {
        let mut mesh = textured_triangle();
        mesh.set_texture(MeshTexture {
            width: 4,
            height: 4,
            rgba: vec![0; 8],
        });

        let mut bytes = Vec::new();
        let written = crate::write::write_mesh(
            &mut bytes,
            &mesh,
            MeshWriteFormat::PlyBinaryLittleEndian,
            MeshWriteOptions::default(),
        )
        .expect("write ply");

        assert!(
            written
                .warnings
                .contains(&MeshWriteWarning::TextureImageNotWritten),
            "the operator has to be told the image was dropped"
        );
        let header_end = bytes
            .windows(b"end_header\n".len())
            .position(|window| window == b"end_header\n")
            .expect("end header");
        let header = String::from_utf8_lossy(&bytes[..header_end]);
        assert!(
            !header.contains("OccluViewTexture"),
            "an unusable image must not be promised:\n{header}"
        );
        // The coordinates are still preserved for the next tool even though the
        // image could not travel, so the mesh keeps its mapping.
        assert!(!written.warnings.contains(&MeshWriteWarning::UvsNotWritten));
        assert!(header.contains("property float s"));
    }

    /// A UV that maps outside the atlas clamps to the edge, exactly as the
    /// renderer's `ClampToEdge` sampler does, instead of reading out of bounds.
    #[test]
    fn a_uv_outside_the_atlas_clamps_to_the_edge() {
        let texture = MeshTexture::new(
            2,
            2,
            vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        );
        // Far outside on both axes clamps to the two opposite corner texels.
        assert_eq!(sample(&texture, [-1.0, -1.0]), [1, 2, 3, 4]);
        assert_eq!(sample(&texture, [2.0, 2.0]), [13, 14, 15, 16]);
        // On the very edge, `ClampToEdge` duplicates the edge texel — exactly
        // what the vertex there shows in the viewer, with no seam.
        assert_eq!(sample(&texture, [0.0, 0.0]), [1, 2, 3, 4]);
        // Dead centre of a texel returns that texel unchanged.
        assert_eq!(sample(&texture, [0.25, 0.25]), [1, 2, 3, 4]);
        assert_eq!(sample(&texture, [0.75, 0.75]), [13, 14, 15, 16]);
    }

    /// Both axes have to be interpolated with their own fraction.
    ///
    /// A 2x2 atlas of four distinct texels, sampled a quarter of the way across
    /// in X and three quarters down in Y. Blending the bottom row with the Y
    /// fraction instead of the X fraction — a transposition — gives 175, so the
    /// two implementations cannot both pass.
    #[test]
    fn both_axes_use_their_own_fraction() {
        let texture = MeshTexture::new(
            2,
            2,
            vec![
                0, 0, 0, 255, // (0,0) black
                200, 200, 200, 255, // (1,0) light grey
                100, 100, 100, 255, // (0,1) mid grey
                255, 255, 255, 255, // (1,1) white
            ],
        );
        // u = 0.375, v = 0.625 on a 2x2 atlas: fx = 0.25, fy = 0.75.
        assert_eq!(sample(&texture, [0.375, 0.625]), [117, 117, 117, 255]);
    }

    /// A non-finite UV is not a coordinate; it must not be read as one.
    #[test]
    fn a_non_finite_uv_is_neutral_white() {
        let texture = MeshTexture::new(1, 1, vec![9, 8, 7, 6]);
        assert_eq!(sample(&texture, [f32::NAN, 0.0]), [255, 255, 255, 255]);
        assert_eq!(sample(&texture, [0.0, f32::INFINITY]), [255, 255, 255, 255]);
    }
}
