.TH OCCLUVIEW-CLI 1 "August 2026" "OccluView" "User Commands"
.SH NAME
occluview-cli \- inspect, convert, repair, and thumbnail 3D meshes
.SH SYNOPSIS
.B occluview-cli
.I COMMAND
.RI [ OPTIONS ]
.SH COMMANDS
.TP
.B thumbnail FILE [-o OUTPUT] [--size PIXELS]
Render a PNG thumbnail.
.TP
.B convert FILE -o OUTPUT
Convert a mesh to STL, PLY, or OBJ according to the output extension.
.TP
.B close-holes FILE -o OUTPUT [--max-diameter MM]
Close eligible boundary loops and write the repaired mesh.
.TP
.B info FILE [FILE ...]
Print format and geometry information.
.TP
.B help
Show command-line help.
.SH OPTIONS
.TP
.BR \-h , " " \-\-help
Show command-line help.
.TP
.BR \-V , " " \-\-version
Show the installed version.
.SH SEE ALSO
.BR occluview (1)
.SH BUGS
Report issues at https://github.com/occlutrace/OccluView/issues.
