use crate::error::HpsError;
use std::env;
use std::fmt;
use zeroize::{Zeroize, ZeroizeOnDrop, Zeroizing};

/// Secret bytes used to decrypt encrypted HPS `CE` blocks.
///
/// The bytes are redacted in `Debug` and zeroized on drop. This does not make
/// an offline client secret impossible to extract; it just keeps accidental
/// leaks out of logs and crash text.
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct HpsSecretKey {
    bytes: Vec<u8>,
}

impl HpsSecretKey {
    /// Construct a Blowfish-compatible HPS key.
    ///
    /// # Errors
    /// Returns [`HpsError::InvalidKey`] when the key length is outside
    /// Blowfish's 4..=56 byte range.
    pub fn from_bytes(bytes: Vec<u8>) -> Result<Self, HpsError> {
        let mut bytes = bytes;
        if let Err(error) = validate_key_len(bytes.len()) {
            bytes.zeroize();
            return Err(error);
        }
        Ok(Self { bytes })
    }

    /// Parse the same human-friendly key syntax used by the legacy native
    /// parser: decimal byte CSV (`1,2,3`) or raw UTF-8 bytes.
    ///
    /// # Errors
    /// Returns [`HpsError::InvalidKey`] if the resulting key is not
    /// Blowfish-compatible.
    pub fn from_config_value(value: &str) -> Result<Self, HpsError> {
        if value.contains(',') {
            let parsed: Option<Vec<u8>> = value
                .split(',')
                .map(str::trim)
                .map(|token| token.parse::<u8>().ok())
                .collect();
            if let Some(bytes) = parsed.filter(|bytes| !bytes.is_empty()) {
                return Self::from_bytes(bytes);
            }
        }
        Self::from_bytes(value.as_bytes().to_vec())
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }
}

impl fmt::Debug for HpsSecretKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("HpsSecretKey")
            .field("bytes", &"<redacted>")
            .finish()
    }
}

/// Supplies the base HPS key for encrypted `CE` files.
pub trait HpsKeyProvider: Sync {
    /// Provider-specific error returned unchanged by [`crate::ReadError`].
    type Error;

    /// Return the base secret key, or `None` when this build/user has no key.
    ///
    /// # Errors
    /// Providers should return an error when the configured key exists but is
    /// malformed or unavailable due to an OS credential-store failure.
    fn base_key(&self) -> Result<Option<HpsSecretKey>, Self::Error>;
}

/// Default public-build provider: no secret material is shipped.
#[derive(Debug, Default, Copy, Clone)]
pub struct NoHpsKeyProvider;

impl HpsKeyProvider for NoHpsKeyProvider {
    type Error = std::convert::Infallible;

    fn base_key(&self) -> Result<Option<HpsSecretKey>, Self::Error> {
        Ok(None)
    }
}

/// Reads an HPS key from process environment.
///
/// This is intended for local/dev/private launch paths. It is never used by the
/// pure parser unless the caller explicitly passes this provider.
#[derive(Debug, Copy, Clone)]
pub struct EnvHpsKeyProvider {
    vars: &'static [&'static str],
}

impl Default for EnvHpsKeyProvider {
    fn default() -> Self {
        Self {
            vars: &[
                "OCCLUVIEW_HPS_ENCRYPTION_KEY",
                "OCCLUVIEW_HPS_KEY",
                "OCCLUTRACE_HPS_ENCRYPTION_KEY",
                "HPS_ENCRYPTION_KEY",
            ],
        }
    }
}

impl HpsKeyProvider for EnvHpsKeyProvider {
    type Error = HpsError;

    fn base_key(&self) -> Result<Option<HpsSecretKey>, Self::Error> {
        for var in self.vars {
            match env::var(var) {
                Ok(value) if !value.trim().is_empty() => {
                    let value = Zeroizing::new(value);
                    return HpsSecretKey::from_config_value(&value).map(Some);
                }
                Ok(_) | Err(env::VarError::NotPresent) => {}
                Err(env::VarError::NotUnicode(_)) => {
                    return Err(super::malformed(format!(
                        "{var} must be valid Unicode key config"
                    )));
                }
            }
        }
        Ok(None)
    }
}

/// Runtime provider for consuming applications and command-line tools.
///
/// Public builds use environment configuration only. Private builds can enable
/// the `private-hps-key` feature and set `OCCLUVIEW_HPS_EMBEDDED_KEY` during
/// compilation; the generated bytes are obfuscated in the binary, not stored in
/// git. This is reverse-engineering friction, not absolute secrecy.
#[derive(Debug, Default, Copy, Clone)]
pub struct RuntimeHpsKeyProvider;

impl HpsKeyProvider for RuntimeHpsKeyProvider {
    type Error = HpsError;

    fn base_key(&self) -> Result<Option<HpsSecretKey>, Self::Error> {
        #[cfg(feature = "private-hps-key")]
        if let Some(key) = embedded_key()? {
            return Ok(Some(key));
        }

        EnvHpsKeyProvider::default().base_key()
    }
}

#[cfg(feature = "private-hps-key")]
mod embedded {
    include!(concat!(env!("OUT_DIR"), "/embedded_hps_key.rs"));
}

#[cfg(feature = "private-hps-key")]
fn embedded_key() -> Result<Option<HpsSecretKey>, HpsError> {
    let len = embedded::EMBEDDED_HPS_KEY_PAYLOAD.len();
    if len == 0 {
        return Ok(None);
    }
    let same_len = embedded::EMBEDDED_HPS_KEY_ORDER.len() == len
        && embedded::EMBEDDED_HPS_KEY_MASK_A.len() == len
        && embedded::EMBEDDED_HPS_KEY_MASK_B.len() == len;
    if !same_len {
        return Err(super::malformed(
            "embedded CE encryption key payload is inconsistent",
        ));
    }
    let mut bytes = vec![0_u8; len];
    for slot in 0..len {
        let original_idx = usize::from(embedded::EMBEDDED_HPS_KEY_ORDER[slot]);
        if original_idx >= len {
            return Err(super::malformed(
                "embedded CE encryption key order is inconsistent",
            ));
        }
        let slot_low = slot.to_le_bytes()[0];
        let salt = embedded::EMBEDDED_HPS_KEY_SALT[slot % embedded::EMBEDDED_HPS_KEY_SALT.len()];
        let salt_mask = salt.rotate_left(u32::from(slot_low & 7));
        let slot_mask = slot_low.wrapping_mul(31).rotate_right(1);
        let decoy_noise = embedded_decoy_noise(slot);
        let decoy_cancel = decoy_noise ^ std::hint::black_box(decoy_noise);
        bytes[original_idx] = embedded::EMBEDDED_HPS_KEY_PAYLOAD[slot]
            ^ embedded::EMBEDDED_HPS_KEY_MASK_A[slot]
            ^ embedded::EMBEDDED_HPS_KEY_MASK_B[slot]
            ^ salt_mask
            ^ slot_mask
            ^ decoy_cancel;
    }
    HpsSecretKey::from_bytes(bytes).map(Some)
}

#[cfg(feature = "private-hps-key")]
fn embedded_decoy_noise(slot: usize) -> u8 {
    let len = embedded::EMBEDDED_HPS_KEY_DECOY_A
        .len()
        .min(embedded::EMBEDDED_HPS_KEY_DECOY_B.len());
    if len == 0 {
        return 0;
    }
    let slot_low = slot.to_le_bytes()[0];
    let left_idx = slot.wrapping_mul(7).wrapping_add(3) % len;
    let right_idx = slot.wrapping_mul(11).wrapping_add(5) % len;
    let noise = embedded::EMBEDDED_HPS_KEY_DECOY_A[left_idx]
        ^ embedded::EMBEDDED_HPS_KEY_DECOY_B[right_idx].rotate_left(u32::from(slot_low & 7))
        ^ slot_low.wrapping_mul(17);
    std::hint::black_box(noise)
}

pub(super) fn validate_key_len(len: usize) -> Result<(), HpsError> {
    if !(4..=56).contains(&len) {
        return Err(HpsError::InvalidKey {
            reason: "CE encryption key must be 4..56 bytes for Blowfish".to_string(),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]

    use super::*;

    #[test]
    fn config_value_accepts_decimal_csv_bytes() {
        let key = HpsSecretKey::from_config_value("1, 2, 3, 4").expect("valid CSV key");
        assert_eq!(key.as_bytes(), &[1, 2, 3, 4]);
    }

    #[test]
    fn config_value_accepts_raw_utf8_bytes() {
        let key = HpsSecretKey::from_config_value("abcd").expect("valid raw key");
        assert_eq!(key.as_bytes(), b"abcd");
    }

    #[cfg(feature = "private-hps-key")]
    #[test]
    fn runtime_provider_reads_generated_embedded_key_when_present() {
        let configured = env::var("OCCLUVIEW_HPS_EMBEDDED_KEY")
            .ok()
            .filter(|value| !value.trim().is_empty());
        let actual = RuntimeHpsKeyProvider.base_key().expect("provider works");
        match configured {
            Some(value) => {
                let expected = HpsSecretKey::from_config_value(&value).expect("valid test key");
                assert_eq!(
                    actual.expect("embedded key exists").as_bytes(),
                    expected.as_bytes()
                );
            }
            None => assert!(actual.is_none()),
        }
    }

    #[cfg(feature = "private-hps-key")]
    #[test]
    fn generated_embedded_layout_contains_decoy_material() {
        let decoy_len = std::hint::black_box(embedded::EMBEDDED_HPS_KEY_DECOY_A.len());
        assert!(decoy_len > 0);
        assert_eq!(decoy_len, embedded::EMBEDDED_HPS_KEY_DECOY_B.len());
        assert!(embedded::EMBEDDED_HPS_KEY_DECOY_A
            .iter()
            .any(|byte| *byte != 0));
        let _ = embedded_decoy_noise(0) ^ embedded_decoy_noise(1);
    }
}
